src/Entity/ForumBan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * Represents a ban or unban action that applies to a user and a forum.
 *
 * @ORM\Entity(repositoryClass="App\Repository\ForumBanRepository")
 * @ORM\Table(name="forum_bans")
 */
class ForumBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="bans")
     *
     * @var Forum
     */
    private $forum;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $expiresAt;

    public function __construct(
        Forum $forum,
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->forum = $forum;
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;

        // since the last ban takes precedence, and because timestamps are used
        // for sorting, we'll use microseconds to hopefully avoid collisions
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', microtime(true));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getForum(): Forum {
        return $this->forum;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    public function getExpiryTime(): ?\DateTime {
        return $this->expiresAt;
    }

    public function isExpired() {
        if ($this->expiresAt === null) {
            return false;
        }

        return $this->expiresAt < \DateTime::createFromFormat('U.u', microtime(true));
    }
}

src/Form/ForumType.php
<?php

namespace App\Form;

use App\Entity\ForumCategory;
use App\Form\Model\ForumData;
use App\Form\Type\HoneypotType;
use App\Form\Type\MarkdownType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

final class ForumType extends AbstractType {
    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker) {
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        if ($options['honeypot']) {
            $builder->add('email', HoneypotType::class);
        }

        /* @var ForumData $data */
        $data = $builder->getData();
        $editing = $data && $data->getEntityId();

        $builder
            ->add('name', TextType::class)
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
            ->add('sidebar', MarkdownType::class, [
                'label' => 'label.sidebar',
            ])
            ->add('category', EntityType::class, [
                'class' => ForumCategory::class,
                'choice_label' => 'name',
                'query_builder' => function (EntityRepository $repository) {
                    return $repository->createQueryBuilder('fc')
                        ->orderBy('fc.name', 'ASC');
                },
                'required' => false,
                'placeholder' => 'forum_form.uncategorized_placeholder',
            ])
        ;

        if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $builder->add('featured', CheckboxType::class, [
                'required' => false,
            ]);
        }

        $builder->add('submit', SubmitType::class, [
            'label' => $editing ? 'forum_form.save' : 'forum_form.create',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => ForumData::class,
            'label_format' => 'forum_form.%name%',
            'honeypot' => true,
            'validation_groups' => function (FormInterface $form) {
                $editing = $form->getData() && $form->getData()->getEntityId();

                return $editing ? ['edit'] : ['create'];
            },
        ]);

        $resolver->setAllowedTypes('honeypot', ['bool']);
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Forum;
use App\Entity\ForumWebhook;
use App\Entity\Moderator;
use App\Entity\User;
use App\Form\ForumAppearanceType;
use App\Form\ForumBanType;
use App\Form\ForumType;
use App\Form\ForumWebhookType;
use App\Form\Model\ForumBanData;
use App\Form\Model\ForumData;
use App\Form\Model\ForumWebhookData;
use App\Form\Model\ModeratorData;
use App\Form\ModeratorType;
use App\Form\PasswordConfirmType;
use App\Repository\ForumBanRepository;
use App\Repository\ForumCategoryRepository;
use App\Repository\ForumLogEntryRepository;
use App\Repository\ForumRepository;
use App\Repository\ForumWebhookRepository;
use App\Repository\SubmissionRepository;
use Doctrine\ORM\EntityManager;
use Ramsey\Uuid\Uuid;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Entity("forum", expr="repository.findOneOrRedirectToCanonical(forum_name, 'forum_name')")
 * @Entity("user", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
 */
final class ForumController extends AbstractController {
    /**
     * @var SubmissionRepository
     */
    private $submissions;

    /**
     * @var bool
     */
    private $enableWebhooks;

    public function __construct(SubmissionRepository $submissions, bool $enableWebhooks) {
        $this->submissions = $submissions;
        $this->enableWebhooks = $enableWebhooks;
    }

    /**
     * Show the front page of a given forum.
     *
     * @param Forum  $forum
     * @param string $sortBy
     *
     * @return Response
     */
    public function front(Forum $forum, string $sortBy, Request $request): Response {
        $submissions = $this->submissions->findSubmissions($sortBy, [
            'forums' => [$forum->getId()],
            'stickies' => true,
        ], $request);

        return $this->render('forum/forum.html.twig', [
            'forum' => $forum,
            'sort_by' => $sortBy,
            'submissions' => $submissions,
        ]);
    }

    public function multi(ForumRepository $fr, string $names, string $sortBy, Request $request) {
        $names = preg_split('/[^\w]+/', $names, -1, PREG_SPLIT_NO_EMPTY);
        $names = array_map(Forum::class.'::normalizeName', $names);
        $names = $fr->findForumNames($names);

        if (!$names) {
            throw $this->createNotFoundException('no such forums');
        }

        $submissions = $this->submissions->findSubmissions($sortBy, [
            'forums' => array_keys($names),
        ], $request);

        return $this->render('forum/multi.html.twig', [
            'forums' => $names,
            'sort_by' => $sortBy,
            'submissions' => $submissions,
        ]);
    }

    /**
     * Create a new forum.
     *
     * @IsGranted("ROLE_USER")
     * @IsGranted("create_forum", statusCode=403)
     *
     * @param Request       $request
     * @param EntityManager $em
     *
     * @return Response
     */
    public function createForum(Request $request, EntityManager $em) {
        $data = new ForumData();

        $form = $this->createForm(ForumType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $forum = $data->toForum($this->getUser());

            $em->persist($forum);
            $em->flush();

            return $this->redirectToRoute('forum', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("moderator", subject="forum", statusCode=403)
     *
     * @param Request       $request
     * @param Forum         $forum
     * @param EntityManager $em
     *
     * @return Response
     */
    public function editForum(Request $request, Forum $forum, EntityManager $em) {
        $data = ForumData::createFromForum($forum);

        $form = $this->createForm(ForumType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateForum($forum);

            $em->flush();

            $this->addFlash('success', 'flash.forum_updated');

            return $this->redirectToRoute('edit_forum', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/edit.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    /**
     * @param Forum   $forum
     * @param string  $sortBy
     * @param Request $request
     *
     * @return Response
     */
    public function feed(Forum $forum, string $sortBy, Request $request) {
        return $this->render('forum/feed.xml.twig', [
            'forum' => $forum,
            'submissions' => $this->submissions->findSubmissions($sortBy, [
                'forums' => [$forum->getId()],
            ], $request),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("ROLE_ADMIN", statusCode=403)
     *
     * @param Request       $request
     * @param Forum         $forum
     * @param EntityManager $em
     *
     * @return Response
     */
    public function delete(Request $request, Forum $forum, EntityManager $em) {
        $form = $this->createForm(PasswordConfirmType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($forum);
            $em->flush();

            $this->addFlash('success', 'flash.forum_deleted');

            return $this->redirectToRoute('front');
        }

        return $this->render('forum/delete.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     *
     * @param Request       $request
     * @param EntityManager $em
     * @param Forum         $forum
     * @param bool          $subscribe
     * @param string        $_format
     *
     * @return Response
     */
    public function subscribe(Request $request, EntityManager $em, Forum $forum, bool $subscribe, string $_format) {
        $this->validateCsrf('subscribe', $request->request->get('token'));

        if ($subscribe) {
            $forum->subscribe($this->getUser());
        } else {
            $forum->unsubscribe($this->getUser());
        }

        $em->flush();

        if ($_format === 'json') {
            return $this->json(['subscribed' => $subscribe]);
        }

        if ($request->headers->has('Referer')) {
            return $this->redirect($request->headers->get('Referer'));
        }

        return $this->redirectToRoute('forum', ['forum_name' => $forum->getName()]);
    }

    /**
     * @param ForumRepository $repository
     * @param int             $page
     * @param string          $sortBy
     *
     * @return Response
     */
    public function list(ForumRepository $repository, int $page = 1, string $sortBy) {
        return $this->render('forum/list.html.twig', [
            'forums' => $repository->findForumsByPage($page, $sortBy),
            'sortBy' => $sortBy,
        ]);
    }

    /**
     * @param ForumCategoryRepository $fcr
     * @param ForumRepository         $fr
     *
     * @return Response
     */
    public function listCategories(ForumCategoryRepository $fcr, ForumRepository $fr) {
        $forumCategories = $fcr->findBy([], ['name' => 'ASC']);
        $uncategorizedForums = $fr->findBy(['category' => null], ['normalizedName' => 'ASC']);

        return $this->render('forum/list_by_category.html.twig', [
            'forum_categories' => $forumCategories,
            'uncategorized_forums' => $uncategorizedForums,
        ]);
    }

    /**
     * Show a list of forum moderators.
     *
     * @param Forum $forum
     * @param int   $page
     *
     * @return Response
     */
    public function moderators(Forum $forum, int $page) {
        return $this->render('forum/moderators.html.twig', [
            'forum' => $forum,
            'moderators' => $forum->getPaginatedModerators($page),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("ROLE_ADMIN", statusCode=403)
     *
     * @param EntityManager $em
     * @param Forum         $forum
     * @param Request       $request
     *
     * @return Response
     */
    public function addModerator(EntityManager $em, Forum $forum, Request $request) {
        $data = new ModeratorData($forum);
        $form = $this->createForm(ModeratorType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $forum->addModerator($data->toModerator());

            $em->flush();

            $this->addFlash('success', 'flash.forum_moderator_added');

            return $this->redirectToRoute('forum_moderators', [
                'forum_name' => $forum->getName(),
            ]);
        }

        return $this->render('forum/add_moderator.html.twig', [
            'form' => $form->createView(),
            'forum' => $forum,
        ]);
    }

    /**
     * @Entity("moderator", expr="repository.findOneBy({'forum': forum, 'id': moderator_id})")
     * @IsGranted("ROLE_USER")
     * @IsGranted("remove", subject="moderator", statusCode=403)
     *
     * @param EntityManager $em
     * @param Forum         $forum
     * @param Request       $request
     * @param Moderator     $moderator
     *
     * @return Response
     */
    public function removeModerator(EntityManager $em, Forum $forum, Request $request, Moderator $moderator) {
        $this->validateCsrf('remove_moderator', $request->request->get('token'));

        $em->remove($moderator);
        $em->flush();

        $this->addFlash('success', 'flash.user_unmodded');

templates/forum/_list_macros.html.twig
{% macro forum_list_header() %}
  <nav class="tabs forum-list-view-selector">
    <ul class="unlistify tabs__bar">
      {% with { active: app.request.attributes.get('_route') == 'forum_list' } %}
        <li class="tabs__tab {{ active ? 'tabs__tab--active' }}">
          <a href="{{ path('forum_list') }}" class="tab tabs__link {{ active ? 'tab--active tabs__link--active' }}">
            {{- 'forum_list.list_view'|trans -}}
          </a>
        </li>
      {% endwith %}
      {% with { active: app.request.attributes.get('_route') == 'forums_by_category' } %}
        <li class="tabs__tab {{ active ? 'tabs__tab--active' }}">
          <a href="{{ path('forums_by_category') }}" class="tab tabs__link {{ active ? 'tab--active tabs__link--active' }}">
            {{- 'forum_list.category_view'|trans -}}
          </a>
        </li>
      {% endwith %}
    </ul>
  </nav>

  <h1 class="page-heading">{{ 'forum_list.page_title'|trans }}</h1>

  {% if is_granted('create_forum') %}
    <p role="navigation">
      <a href="{{ path('create_forum') }}" class="button">{{ 'forum_list.create_forum'|trans }}</a>
    </p>
  {% elseif is_granted('ROLE_USER') %}
    <div class="alert alert--notice">
      <p>{{ 'flash.you_cannot_create_forums_yet'|trans }}</p>
    </div>
  {% endif %}
{% endmacro %}

templates/forum/add_moderator.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes %}
  add-moderators-page
{% endblock %}

{% block title %}
  {{ 'add_moderator.title'|trans({'%forum%': forum.name}) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ form(form) }}
{% endblock %}

templates/forum/add_webhook.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes 'add-forum-webhook-page' %}
{% block title 'title.add_forum_webhook'|trans({'%forum%': '/f/'~forum.name}) %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.add_forum_webhook'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
        path('forum', {forum_name: forum.name})|e,
        forum.name|e
    ) })|raw }}
  </h1>

  {{ include('forum/_webhook_form.html.twig', {form: form}, with_context=false) }}
{% endblock %}

templates/forum/appearance.html.twig
{% extends 'forum/base.html.twig' %}

{% block title 'title.forum_appearance'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}
{% block page_classes 'forum-appearance-page' %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.forum_appearance'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('forum', {forum_name: forum.name})|escape,
      forum.name|escape
    )})|raw }}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.theme, {attr: {class: 'select2'}}) }}

    {# todo: some navigation widget thing #}
    <nav>
      <ul>
        <li><a href="{{ path('themes') }}">{{ 'nav.themes'|trans }}</a></li>
        <li><a href="{{ path('create_theme') }}">{{ 'nav.create_theme'|trans }}</a></li>
      </ul>
    </nav>
  {{ form_end(form) }}
{% endblock %}

templates/forum/ban_history.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes 'forum-ban-history-page' %}
{% block title 'title.showing_ban_history_for_user_in_forum'|trans({
  '%user%': '/u/'~user.username,
  '%forum%': '/f/'~forum.name,
}) %}

{% block head %}
  {{ parent() }}
  {{ include('_includes/meta_pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <table class="table">
    <thead>
      <tr>
        <th class="table__shrink">{{ 'label.action'|trans }}</th>
        <th>{{ 'label.reason'|trans }}</th>
        <th class="table__shrink">{{ 'label.banned'|trans }}</th>
        <th class="table__shrink">{{ 'label.expires'|trans }}</th>
      </tr>
    </thead>
    <tbody>
      {% for ban in bans %}
        <tr>
          <td class="table__shrink">{{ (ban.ban ? 'label.ban' : 'label.unban')|trans }}</td>
          <td>{{ ban.reason }}</td>
          <td class="table__shrink">
            {% with {date: ban.timestamp|localizeddate('long', 'short')} %}
              <time datetime="{{ ban.timestamp|date('c') }}" class="relative-time" title="{{ date }}">
                {{- date -}}
              </time>
            {% endwith %}
          </td>
          <td class="table__shrink">
            {% if ban.expiryTime %}
              {% with {date: ban.expiryTime|localizeddate('long', 'short')} %}
                <time datetime="{{ ban.expiryTime|date('c') }}" class="relative-time" title="{{ date }}">
                  {{- date -}}
                </time>
              {% endwith %}
            {% else %}
              {{ 'label.never'|trans }}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {{ include('_includes/pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

templates/forum/base.html.twig
{% extends 'base.html.twig' %}

{% block head %}
  <link rel="alternate" type="application/atom+xml" href="{{ path('forum_feed', {forum_name: forum.name}) }}" title="{{ forum.name }}">
{% endblock %}

{% block stylesheets %}
  {% if (app.user.showCustomStylesheets ?? true) and forum.theme %}
    {{ include('_includes/stylesheets.html.twig', {
      theme: forum.theme,
      night_mode: app.user.nightMode ?? false
    }, with_context=false) }}
  {% else %}
    {{ parent() }}
  {% endif %}
{% endblock %}

{% block sidebar %}
  <section class="sidebar__section sidebar__section--forum-meta forum-meta">
    <h1 class="sidebar__title forum-title"><a href="{{ path('forum', {forum_name: forum.name}) }}">{{ forum.title }}</a></h1>

    {% if is_granted('ROLE_USER') %}
      {% from 'forum/_macros.html.twig' import subscribe_button %}
      {% set subscribed = forum.subscribed(app.user) %}
      <form action="{{ path(subscribed ? 'unsubscribe' : 'subscribe', {forum_name: forum.name}) }}"
            method="POST"
            class="form subscribe-form"
            data-forum="{{ forum.name }}">
        <input type="hidden" name="token" value="{{ csrf_token('subscribe') }}">

        <div class="form__row">
          {{ subscribe_button(forum, subscribed, false) }}
        </div>
      </form>
    {% endif %}

    {% if forum.sidebar is not empty %}
      <div class="forum-sidebar-content">{{ forum.sidebar|cached_markdown({ context: 'forum_sidebar', forum: forum })|raw }}</div>
    {% endif %}
  </section>

  {% if app_external_search_enabled() %}
    {% include '_includes/search.html.twig' with {
      forum_path: path('forum', {forum_name: forum.name})
    } %}
  {% endif %}

  {% if is_granted('ROLE_USER') %}
    {% set is_hidden = app.user.hidingForum(forum) %}
    <details class="sidebar__section">
      <summary class="sidebar__title">{{ 'heading.hide_this_forum'|trans }}</summary>

      <p class="dimmed">{{ 'help.hidden_forums'|trans }}</p>

      <form action="{{ path(is_hidden ? 'unhide_forum' : 'hide_forum', {username: app.user.username, forum: forum.id}) }}" method="POST">
        <input type="hidden" name="token" value="{{ csrf_token('hide_forum') }}">

        <p>
          <button class="button button--secondary" title="">
            {{ is_hidden ? 'action.unhide'|trans : 'action.hide'|trans }}
          </button>
        </p>
      </form>
    </details>
  {% endif %}

  <section class="sidebar__section sidebar__section--forum-manage forum-manage">
    <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>

    {# sorted nav items #}
    {% with { items: {} } %}
      {% set item %}
        <li><a href="{{ path('forum_bans', {forum_name: forum.name}) }}">{{ 'nav.bans'|trans }}</a></li>
      {% endset %}
      {% set items = items|merge({('nav.bans'|trans): item}) %}

      {% set item %}
        <li><a href="{{ path('moderation_log', {forum_name: forum.name}) }}">{{ 'nav.moderation_log'|trans }}</a></li>
      {% endset %}
      {% set items = items|merge({('nav.moderation_log'|trans): item}) %}

      {% if is_granted('moderator', forum) %}
        {% set item %}
          <li><a href="{{ path('edit_forum', {forum_name: forum.name}) }}">{{ 'forum.edit'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('forum.edit'|trans): item}) %}

        {% set item %}
          <li><a href="{{ path('forum_appearance', {forum_name: forum.name}) }}">{{ 'nav.appearance'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('nav.appearance'|trans): item}) %}

        {% if app_webhooks_enabled() %}
          {% set item %}
            <li><a href="{{ path('forum_webhooks', {forum_name: forum.name}) }}">{{ 'nav.webhooks'|trans }}</a></li>
          {% endset %}
          {% set items = items|merge({('nav.webhooks'|trans): item}) %}
        {% endif %}
      {% endif %}

      {% if is_granted('ROLE_ADMIN') %}
        {% set item %}
          <li><a href="{{ path('add_moderator', {forum_name: forum.name}) }}">{{ 'forum.add_moderator'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('forum.add_moderator'|trans): item}) %}

        {% set item %}
          <li><a href="{{ path('delete_forum', {forum_name: forum.name}) }}">{{ 'nav.delete_forum'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('nav.delete_forum'|trans): item}) %}
      {% endif %}

      <ul>
        {% for key in items|keys|sort %}
          {{ items[key] }}
        {% endfor %}
      </ul>
    {% endwith %}
  </section>

  {% if forum.moderators|length > 0 %}
    <section class="sidebar__section sidebar__section--forum-moderators forum-moderators">
      <h1 class="sidebar__title"><a href="{{ path('forum_moderators', {forum_name: forum.name}) }}">{{ 'forum.moderators'|trans }}</a></h1>
      <ul>
        {% for moderator in forum.moderators %}
          <li>
            <a href="{{ path('user', {username: moderator.user.username}) }}">
              {{- moderator.user.username -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

templates/forum/delete.html.twig
{% extends 'forum/base.html.twig' %}

{% block title 'title.delete_forum'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}
{% block page_classes 'forum-delete-page' %}

{% block body %}
  <h1 class="page-heading">
    {{- 'title.delete_forum'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('forum', {forum_name: forum.name})|escape,
      forum.name|escape
      )})|raw
    -}}
  </h1>

  <p>{{ 'help.delete_forum_warning'|trans }}</p>

  {{ form(form) }}
{% endblock %}

templates/forum/edit.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes %}edit-forum-page{% endblock %}
{% block title 'edit_forum.title'|trans({'%forum%': '/f/'~forum.name}) %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.editing_forum'|trans({
      '%forum%': '<a href="%s">/f/%s</a>'|format(path('forum', {forum_name: forum.name})|e, forum.name|e)
    })|raw }}
  </h1>

  {{ include('forum/_form.html.twig', {form: form}, with_context=false) }}
{% endblock %}

{% block javascripts %}
  {{ parent() }}

  <script>
    $('.delete-forum').click(function () {
      return confirm(Translator.trans('forum_form.confirm_delete'));
    });
  </script>
{% endblock %}